export const LOAD_USERS = "LOAD_USERS";
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const REMOVE_USER = "REMOVE_USER";
export const CLEAR_RESPONSE_MESSAGE = "CLEAR_EDIT_USER_MESSAGE";
export const CLEAR_ADD_MESSAGE = "CLEAR_ADD_MESSAGE";
